addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - jam
      - gcc-4.8
      - g++-4.8
      - gcc-6
      - g++-6
      - libsdl1.2-dev
      - libsdl-mixer1.2-dev
      - libsdl-sound1.2-dev

env:
  matrix:
    - CC=gcc-4.8 CXX=g++-4.8
    - CC=gcc-6 CXX=g++-6
    - CC=clang CXX=clang++

script:
  - jam -sC++=$CXX -sCC=$CC -j4
